#include<iostream>
#include<string>
#include<algorithm>
#include<vector>
#include<iomanip>
#include<math.h>
#include<complex>
#include<queue>
#include<deque>
#include<stack>
#include<map>
#include<set>
#include<bitset>
#include<functional>
#include<assert.h>
#include<numeric>
using namespace std;
#define REP(i,m,n) for(int i=(int)(m) ; i < (int) (n) ; ++i )
#define rep(i,n) REP(i,0,n)
using ll = long long;
const int inf=1e9+7;
const ll longinf=1LL<<60 ;
const ll mod=1e9+7 ;


// // const long long MOD = 1000003;
// // // 
// // void solve(long long Q, std::vector<long long> x, std::vector<long long> d, std::vector<long long> n){

// }
// 
// Generated by 1.1.4 https://github.com/kyuridenamida/atcoder-tools  (tips: You use the default template now. You can remove this line by using your custom template)
int main(){
    //     // long long Q;
    scanf("%lld",&Q);
    std::vector<long long> x(Q);
    std::vector<long long> d(Q);
    std::vector<long long> n(Q);
    for(int i = 0 ; i < Q ; i++){
        scanf("%lld",&x[i]);
        scanf("%lld",&d[i]);
        scanf("%lld",&n[i]);
    }
    // solve(Q, std::move(x), std::move(d), std::move(n));
    //     // return 0;
}
