#include<iostream>
#include<string>
#include<algorithm>
#include<vector>
#include<iomanip>
#include<math.h>
#include<complex>
#include<queue>
#include<deque>
#include<stack>
#include<map>
#include<set>
#include<bitset>
#include<functional>
#include<assert.h>
#include<numeric>
using namespace std;
#define REP(i,m,n) for(int i=(int)(m) ; i < (int) (n) ; ++i )
#define rep(i,n) REP(i,0,n)
using ll = long long;
const int inf=1e9+7;
const ll longinf=1LL<<60 ;
const ll mod=1e9+7 ;


// // // const string YES = "Yes";
// // // const string NO = "No";
// 
// // void solve(long long N, long long Q, std::vector<long long> P, std::vector<long long> A, std::vector<long long> B){

// }
// 
// Generated by 1.1.4 https://github.com/kyuridenamida/atcoder-tools  (tips: You use the default template now. You can remove this line by using your custom template)
int main(){
    //     // long long N;
    scanf("%lld",&N);
    long long Q;
    scanf("%lld",&Q);
    std::vector<long long> P(Q);
    std::vector<long long> A(Q);
    std::vector<long long> B(Q);
    for(int i = 0 ; i < Q ; i++){
        scanf("%lld",&P[i]);
        scanf("%lld",&A[i]);
        scanf("%lld",&B[i]);
    }
    // solve(N, Q, std::move(P), std::move(A), std::move(B));
    //     // return 0;
}
