#include <bits/stdc++.h>
using namespace std;


void solve(long long S){

}

// Generated by 1.1.4 https://github.com/kyuridenamida/atcoder-tools  (tips: You use the default template now. You can remove this line by using your custom template)
int main(){
    long long S;
    scanf("%lld",&S);
    solve(S);
    return 0;
}
