#include<iostream>
#include<string>
#include<algorithm>
#include<vector>
#include<iomanip>
#include<math.h>
#include<complex>
#include<queue>
#include<deque>
#include<stack>
#include<map>
#include<set>
#include<bitset>
#include<functional>
#include<assert.h>
#include<numeric>
using namespace std;
#define REP(i,m,n) for(int i=(int)(m) ; i < (int) (n) ; ++i )
#define rep(i,n) REP(i,0,n)
// using ll = long long;
typedef long long ll;
const int inf=1e9+7;
const ll longinf=1LL<<60 ;
const ll mod=1e9+7 ;


// Generated by 1.1.4 https://github.com/kyuridenamida/atcoder-tools  (tips: You use the default template now. You can remove this line by using your custom template)
ll dp[100010][3];
int main(){
    long long N;
    cin >> N;

    ll ary[N][3];
    // cppはlongのデフォルト値が０
    // dp[0][0] = 0;
    // dp[0][1] = 0;
    // dp[0][2] = 0;
    rep(i, N) rep(j,3) cin >> ary[i][j];

    rep(i, N) {
        dp[i+1][0] = ary[i][0] + max(dp[i][1], dp[i][2]);
        dp[i+1][1] = ary[i][1] + max(dp[i][2], dp[i][0]);
        dp[i+1][2] = ary[i][2] + max(dp[i][0], dp[i][1]);
    }

    cout << max(dp[N][0], max(dp[N][1], dp[N][2])) <<endl;
}
