#include <bits/stdc++.h>
#include <string>
#include <iostream>
using namespace std;


void solve(string S){
    int count1 = 0;
    for (int i=0; i<S.length();i++) {
        if (i%2 != S[i] - '0') {
            count1 ++;
        }
    }
    int count2 = S.length() - count1;
    if (count1 >= count2) {
        cout << count2 << endl;
    } else {
        cout << count1 << endl;
    }
}

// Generated by 1.1.4 https://github.com/kyuridenamida/atcoder-tools  (tips: You use the default template now. You can remove this line by using your custom template)
int main(){
    string S;
    cin >> S;
    solve(S);
    return 0;
}
