#include <bits/stdc++.h>
#include <math.h>
using namespace std;


void solve(long long M, long long K){
    if (M == 1) {
        if (K == 0) {
            cout << "0 0 1 1" << endl;
        }
        else
        {
            cout << -1 << endl;
        }
    }
    else if (K >= pow(2, M)) {
        cout << -1 << endl;
    }
    else if (K == 0) {
        for (int i = 0; i<pow(2,M)-1 ;i++) {
            cout << i << " " << i << " ";
        }
        cout << pow(2,M) -1 << " " << pow(2,M) -1 << endl;
    }
    else
    {
        for (int i = 0; i<pow(2,M) ;i++) {
            if (i != K) {
                cout << i << " ";
            }
        }
        cout << K << " ";
        for (int i = pow(2,M)-1; i>=0 ;i--) {
            if (i != K) {
                cout << i << " ";
            }
        }
        cout << K << endl;

    }
    
}

// Generated by 1.1.4 https://github.com/kyuridenamida/atcoder-tools  (tips: You use the default template now. You can remove this line by using your custom template)
int main(){
    long long M;
    scanf("%lld",&M);
    long long K;
    scanf("%lld",&K);
    solve(M, K);
    return 0;
}
