#include<iostream>
#include<string>
#include<algorithm>
#include<vector>
#include<iomanip>
#include<math.h>
#include<complex>
#include<queue>
#include<deque>
#include<stack>
#include<map>
#include<set>
#include<bitset>
#include<functional>
#include<assert.h>
#include<numeric>
using namespace std;
#define REP(i,m,n) for(int i=(int)(m) ; i < (int) (n) ; ++i )
#define rep(i,n) REP(i,0,n)
using ll = long long;
const int inf=1e9+7;
const ll longinf=1LL<<60 ;
const ll mod=1e9+7 ;

ll dp[110][1010];

void solve(long long N, long long W, long long w[], long long v[]){
    REP(i, 1, 1010) dp[0][i] = longinf;
    REP(i, 1, N+1) {
        rep(j, 1010) {
            if (j-v[i-1]>=0) {
                dp[i][j] = min(dp[i-1][j], dp[i-1][j-v[i-1]]+w[i-1]);
            }
            else
            {
                dp[i][j] = dp[i-1][j];
            }
        }
    }
    // rep(i,N+1) rep(j,100) {
    //     cout << i << " " << j << " " << dp[i][j] << endl; 
    // } 
    ll ans=0;
    rep(i,1010) {
        if (dp[N][i] <= W) {
            ans = i;
        }
    }
    cout << ans << endl;
}

// Generated by 1.1.4 https://github.com/kyuridenamida/atcoder-tools  (tips: You use the default template now. You can remove this line by using your custom template)
int main(){
    long long N;
    cin >> N;
    long long W;
    cin >> W;
    long long w[N];
    long long v[N];
    rep(i,N) cin >> w[i] >> v[i];
    solve(N, W, w, v);
    // return 0;
}
