#include<iostream>
#include<string>
#include<algorithm>
#include<vector>
#include<iomanip>
#include<math.h>
#include<complex>
#include<queue>
#include<deque>
#include<stack>
#include<map>
#include<set>
#include<bitset>
#include<functional>
#include<assert.h>
#include<numeric>
using namespace std;
#define REP(i,m,n) for(int i=(int)(m) ; i < (int) (n) ; ++i )
#define rep(i,n) REP(i,0,n)
using ll = long long;
const int inf=1e9+7;
const ll longinf=1LL<<60 ;
const ll mod=1e9+7 ;


// // // 
// // void solve(long long N, long long X, std::vector<long long> b, std::vector<long long> l, std::vector<long long> u){

// }
// 
// Generated by 1.1.4 https://github.com/kyuridenamida/atcoder-tools  (tips: You use the default template now. You can remove this line by using your custom template)
int main(){
    //     // long long N;
    scanf("%lld",&N);
    long long X;
    scanf("%lld",&X);
    std::vector<long long> b(N);
    std::vector<long long> l(N);
    std::vector<long long> u(N);
    for(int i = 0 ; i < N ; i++){
        scanf("%lld",&b[i]);
        scanf("%lld",&l[i]);
        scanf("%lld",&u[i]);
    }
    // solve(N, X, std::move(b), std::move(l), std::move(u));
    //     // return 0;
}
