#include <bits/stdc++.h>
using namespace std;


void solve(long long a, long long b, long long c, long long d, long long e, long long k){
    bool flag = true;
    if (e-a > k) flag = false;
    if (flag) {
        cout << "Yay!" << endl;
    }
    else
    {
        cout << ":(" << endl;
    }
    
}

// Generated by 1.1.4 https://github.com/kyuridenamida/atcoder-tools  (tips: You use the default template now. You can remove this line by using your custom template)
int main(){
    long long a;
    scanf("%lld",&a);
    long long b;
    scanf("%lld",&b);
    long long c;
    scanf("%lld",&c);
    long long d;
    scanf("%lld",&d);
    long long e;
    scanf("%lld",&e);
    long long k;
    scanf("%lld",&k);
    solve(a, b, c, d, e, k);
    return 0;
}
