#include <bits/stdc++.h>
#include <algorithm>
using namespace std;


void solve(long long A, long long B, long long C, long long D, long long E){
    int count10 = 0;
    long long amari = 10;
    count10 += A/10;
    count10 += B/10;
    count10 += C/10;
    count10 += D/10;
    count10 += E/10;
    if (A%10 != 0) {
        count10 += 1;
        amari = min({amari, A%10});
    }
    if (B%10 != 0) {
        count10 += 1;
        amari = min({amari, B%10});
    }
    if (C%10 != 0) {
        count10 += 1;
        amari = min({amari, C%10});
    }
    if (D%10 != 0) {
        count10 += 1;
        amari = min({amari, D%10});
    }
    if (E%10 != 0) {
        count10 += 1;
        amari = min({amari, E%10});
    }
    cout << count10 * 10 - 10 + amari << endl;
}

// Generated by 1.1.4 https://github.com/kyuridenamida/atcoder-tools  (tips: You use the default template now. You can remove this line by using your custom template)
int main(){
    long long A;
    scanf("%lld",&A);
    long long B;
    scanf("%lld",&B);
    long long C;
    scanf("%lld",&C);
    long long D;
    scanf("%lld",&D);
    long long E;
    scanf("%lld",&E);
    solve(A, B, C, D, E);
    return 0;
}
