#include <bits/stdc++.h>
#include <algorithm>
#include <string>
using namespace std;


void solve(long long N, std::vector<vector<long long>> ary){
    vector<vector<long long> >  dp;
    dp[0][0] = 0
    dp[0][1] = 
}

// Generated by 1.1.4 https://github.com/kyuridenamida/atcoder-tools  (tips: You use the default template now. You can remove this line by using your custom template)
int main(){
    long long N;
    std::vector<vector<long long> > ary(N);
    cin >> N;
    for(int i = 0 ; i < N ; i++){
        long long a,b;
        cin >> a >> b;
        if (a < b) swap(a,b);
        vector<long long> item;
        item[0] = a;
        item[1] = b;
        ary[i] = item;
    }
    solve(N, ary);
    return 0;
}
