#include<iostream>
#include<string>
#include<algorithm>
#include<vector>
#include<iomanip>
#include<math.h>
#include<complex>
#include<queue>
#include<deque>
#include<stack>
#include<map>
#include<set>
#include<bitset>
#include<functional>
#include<assert.h>
#include<numeric>
using namespace std;
#define REP(i,m,n) for(int i=(int)(m) ; i < (int) (n) ; ++i )
#define rep(i,n) REP(i,0,n)
using ll = long long;
const int inf=1e9+7;
const ll longinf=1LL<<60 ;
const ll mod=1e9+7 ;


// Generated by 1.1.4 https://github.com/kyuridenamida/atcoder-tools  (tips: You use the default template now. You can remove this line by using your custom template)
int main(){
    std::string str;
    std::cin >> str;
    
    std::reverse(str.begin(), str.end());
    // cout << str << endl;
    ll ans = 0;
    ll cnt = 0;
    bool horyu = false;

    for (int i = 0; i < str.length(); i++) {
        if (str[i] == 'B') {
            if (horyu) {
                cnt += 1;
            }
            else
            {
                cnt = 0;
            }
            horyu = false;
        }
        else if (str[i] == 'A')
        {
            if (horyu) {
                cnt = 0;
            }
            ans += cnt;
            horyu = false;
        }
        else if (str[i] == 'C')
        {
            if (horyu) {
                cnt = 0;
            }
            horyu = true;
        }
        // cout << ans << endl;
    }
    // cout << "ans: " << ans << endl;
    cout << ans << endl;
}

